name: Keep Supabase Awake

on:
  schedule:
    # This schedules the task to run automatically every Monday and Thursday at midnight UTC
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # This allows you to manually press a button to run it whenever you want

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Make a request to the Supabase Database REST API
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
